# Site settings
title: TrainLink
description: Smart Workout Tracking & Scheduling
url: https://trainlink.eu
baseurl: ""

# GitHub Pages settings
permalink: pretty
include: [".htaccess", "_headers", "_redirects", ".nojekyll"]
exclude: ["netlify.toml", "firebase-security-rules.txt"]

# Build settings
markdown: kramdown
plugins:
  - jekyll-redirect-from 