# Netlify configuration for TrainLink
# NOTE: This file should be modified when switching between development and production modes

# Production context
[build]
  publish = "."

# DEVELOPMENT MODE: Comment out these redirects during development to prevent redirection loops
# PRODUCTION MODE: Uncomment these redirects for production deployment

# Redirects and rewrites for clean URLs - COMMENTED OUT FOR DEVELOPMENT
# [[redirects]]
#   from = "/"
#   to = "/pages/index.html"
#   status = 200

# [[redirects]]
#   from = "/app"
#   to = "/pages/app.html"
#   status = 200

# [[redirects]]
#   from = "/login"
#   to = "/pages/login.html"
#   status = 200

# [[redirects]]
#   from = "/register"
#   to = "/pages/register.html"
#   status = 200

# [[redirects]]
#   from = "/profile"
#   to = "/pages/profile.html"
#   status = 200

# [[redirects]]
#   from = "/privacy"
#   to = "/pages/privacy-policy.html"
#   status = 200

# [[redirects]]
#   from = "/terms"
#   to = "/pages/terms-of-service.html"
#   status = 200

# [[redirects]]
#   from = "/stats"
#   to = "/pages/stats.html"
#   status = 200

# [[redirects]]
#   from = "/devices"
#   to = "/pages/devices.html"
#   status = 200

# [[redirects]]
#   from = "/not-found"
#   to = "/pages/404.html"
#   status = 200

# Handle 404 errors
# [[redirects]]
#   from = "/*"
#   to = "/pages/404.html"
#   status = 404

# Headers for security and optimization - ACTIVE IN BOTH MODES
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self' https://www.googletagmanager.com https://www.gstatic.com https://www.googleapis.com https://pagead2.googlesyndication.com https://firestore.googleapis.com; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.gstatic.com https://www.googleapis.com https://pagead2.googlesyndication.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://img.youtube.com https://i.ytimg.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.googleapis.com https://*.firebaseio.com; frame-src 'self' https://www.youtube.com;"

# Cache control for static assets - ACTIVE IN BOTH MODES
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=2592000" # 30 days

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=2592000" # 30 days

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000" # 1 year

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000" # 1 year

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000" # 1 year 